# Generated by Django 2.2.1 on 2019-05-12 16:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('direction', models.SmallIntegerField(choices=[(1, 'Доход'), (-1, 'Расход')], default=-1)),
                ('account', models.CharField(choices=[('default', 'Дефолтный'), ('storage', 'Сбережения'), ('unexpected', 'Неожиданные траты')], default='default', max_length=10)),
                ('receipt_photo', models.ImageField(blank=True, null=True, upload_to='money/receipts/%Y/%m/%d/')),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='PlanExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('is_bought', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('date_from',),
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('product_name', models.CharField(max_length=255)),
                ('product_type', models.CharField(choices=[('clothes', 'Одежда'), ('foodstuff', 'Продукты'), ('required_periodic', 'Обязательные периодические'), ('baby', 'На Макса'), ('plan', 'Запланированные траты'), ('debt', 'Долги'), ('medicine', 'Медицина'), ('personal', 'Личные'), ('gifts', 'Подарки'), ('leisure', 'Развлечения')], max_length=30)),
                ('wasted', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='money.MoneyMovement')),
                ('plan_expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='money.PlanExpense')),
            ],
            options={
                'ordering': ('movement__date',),
            },
        ),
    ]
